source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'rspec-rails'
gem 'refinerycms'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'refinerycms-i18n', '~> 2.0.0'


